# Generated by Django 4.1.2 on 2022-10-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_level_name_alter_sublevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublevel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='directory.level'),
        ),
    ]
